[package]
name = "advent_of_code_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.22", features = ["derive"] }
itertools = "0.10.5"
lazy_static = "1.4.0"
ndarray = "0.15.6"
regex = "1.7.0"
